### ISSUE TITLE
Strategy Word Confusion in QuinoaBaseVault 

### ISSUE THREAD

**Issue by wakii** [QuinoaDao/protocol#2]
QuinoaBaseVault에서 struct로 쓰이는 Strategy와 addStrategy, activeStrategy 등에서 calldata로 쓰이는 Strategy Contract 사이에 용어 중복.

둘 중 하나 다른 용어로 변경 필요.(Struct 이름 변경 권장)
- IQuinoaBaseVault의 경우 Strategy Contract를 기준으로 작성.

**Comment by Seomingyun** [comment]
Struct이름 : Strategy -> StrategyAttr
parameter 중 strategy의 address를 받아오는 경우 : strategy -> strategyAddr
