### ISSUE TITLE
Can't find an member in IERC20

### ISSUE THREAD

**Issue by wakii** [QuinoaDao/protocol#4]
https://github.com/QuinoaDao/protocol/blob/6087a6e185b8846668771bd73845d87431ba7071/contracts/QuinoaBaseVault.sol#L188

`_asset`이 IERC20이라 decimal을 사용이 어려운데, 이부분 rounding 때문에 필요한건가요?? 
이전 코드 보니까, IERC20Metadata로 했더라고요?? 

```shell
TypeError: Member "decimals" not found or not visible after argument-dependent lookup in contract IERC20.
   --> contracts/QuinoaBaseVault.sol:188:49:
    |
188 |             ? assets.mulDiv(10**decimals(), 10**_asset.decimals(), rounding)
    |                                                 ^^^^^^^^^^^^^^^
```

**Comment by Seomingyun** [comment]
1. 해당 코드는 yearn, rary 등을 참고한 코드임 
    -> asset이나 totalSuply가 0이라면 1:1로 share를 반환해주어야 하는데, 이를 수학적으로 계산하기 위한 수식임
         실제로는 asset의 deciaml과 vault의 decimal을 같게 맞춰주기 때문에 실질적으로는 입력으로 받은 asset(asset의 양)과 같은 값을 반환함 (아닌 경우도 있겠지만 -> constructer 참고, 그런 경우는 거의 없을 거라고 생각함)

2. 이전 version에서 _asset으로 metadata를 사용한건 rary를 참고해서 코드를 구현했기 때문인데, 이번에 바꾸면서 최대한 ERC4626의 구현에 맞추려고 함. 그래서 차이가 생긴 것.

3. 이 함수는 이전 version의 vault에서 그대로 갖고옴. 크게 달라지는 로직이 없다고 생각했기 때문.
  다만 이번 basevault에 대해서 test를 아직 진행하지 않은 거라서 이런 아다리가 안맞는 부분이 있을 수 있음. 계속해서 수정해야 함 (먼저 발견했을 때 list 작성해주거나 수정해주면 감사하겠다!)

**Comment by Seomingyun** [comment]
찾아보니까 ERC20Metadata가 IERC20을 상속받은거라서 IERC20Metadata로 바꿔도 큰 문제는 생기지 않을 거 같은데 혹시 IERC20Metadata로 바꾸면 무슨 문제가 생기는지 알려주면 감사하겟음 ~~!
